//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Gracz : Postać, Ruch
{
	public virtual void Kolizja()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Sterowanie()
	{
		throw new System.NotImplementedException();
	}

}

