//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Plansza : Generowanie
{
	public virtual Obiekt Obiekt
	{
		get;
		set;
	}

	public virtual void Generuj_Formatke()
	{
		throw new System.NotImplementedException();
	}

}

