//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Postać
{
	public virtual int HP
	{
		get;
		set;
	}

	public virtual int WspX
	{
		get;
		set;
	}

	public virtual int WspY
	{
		get;
		set;
	}

}

